from pathlib import Path

from medusa.model.services import (
    ComposeFile,
    GeneratedEnvFile,
)
from medusa.render.templates import render_template


def _render_env_file(env_file: GeneratedEnvFile) -> str:
    lines = ["# Generated by Medusa. Do not edit manually."]
    lines.extend(f"{key}={value}" for key, value in sorted(env_file.values.items()))
    return "\n".join(lines) + "\n"


def _render_compose_file(
    compose_file: ComposeFile,
    templates_dir: Path,
) -> str:
    return render_template(
        templates_dir,
        "compose/compose.yaml.j2",
        {"compose": compose_file},
    )
