from pathlib import Path

from medusa.model.services import (
    ComposeFile,
    GeneratedEnvFile,
    ServicesModel,
)
from medusa.render.templates import render_template


def render_compose(
    model: ServicesModel,
    templates_dir: Path,
    generated_dir: Path,
) -> dict[Path, str]:
    compose_files = {
        _compose_path(generated_dir, compose_file): _render_compose_file(
            compose_file, templates_dir
        )
        for compose_file in model.compose
    }
    env_files = {
        _env_file_path(generated_dir, env_file): _render_env_file(env_file)
        for env_file in model.env_files
    }
    data_dirs = {
        generated_dir / "compose-data-dirs.yaml": render_template(
            templates_dir,
            "compose/data-dirs.yaml.j2",
            {"data_dirs": model.data_dirs},
        )
    }
    return {**compose_files, **env_files, **data_dirs}


def _compose_path(generated_dir: Path, compose_file: ComposeFile) -> Path:
    if compose_file.stack is None:
        return generated_dir / "compose" / f"{compose_file.host}.yaml"

    return generated_dir / "compose" / compose_file.stack / "docker-compose.yml"


def _env_file_path(generated_dir: Path, env_file: GeneratedEnvFile) -> Path:
    if env_file.stack is None:
        return generated_dir / "compose" / env_file.host / env_file.path

    return generated_dir / "compose" / env_file.stack / env_file.path


def _render_env_file(env_file: GeneratedEnvFile) -> str:
    lines = ["# Generated by Medusa. Do not edit manually."]
    lines.extend(f"{key}={value}" for key, value in sorted(env_file.values.items()))
    return "\n".join(lines) + "\n"


def _render_compose_file(
    compose_file: ComposeFile,
    templates_dir: Path,
) -> str:
    return render_template(
        templates_dir,
        "compose/compose.yaml.j2",
        {"compose": compose_file},
    )
